-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVqUqSZyLFYk9Mbk1
iJf/ItEprecJg3b5B8jMT+zTYwSgCgYIKoZIzj0DAQehRANCAASuCvyfBD0HePZy
zoGXrMuc0zlp2VLy6c3aJ/mBunPMXk27CE9s8qjdigZjeNs/pAAFHU79TeoEPxeb
QsTWCNDf
-----END PRIVATE KEY-----